# file a descargar ruta con esqueletos
data_root: "./data/ucf101_skeletons"

#clases seleccionadas
classes:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"

#training
seed: 42
val_ratio: 0.2
num_workers: 4
pin_memory: true

#secuencias
T: 64
J: 17
pelvis_index: 0
height_pair: [5, 11]

#model
hidden_size: 128
num_layers: 1

# optimize
lr: 0.001
epochs: 15
batch_size: 64
label_smoothing: 0.0
dropout: 0.0
